/*
 * Copyright (c) 2022 by multiple authors
 *
 * File name: BufferedImageSenderPayload.java
 * Last modified: 31/10/2022, 19:12
 * Project name: jmps-library
 *
 * Licensed under the MIT license; you may not use this file except in compliance with the License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL
 * COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.
 */

package pl.miloszgilga.lib.jmpsl.gfx.sender;

import lombok.*;

import pl.miloszgilga.lib.jmpsl.gfx.IBufferedImagePayload;
import pl.miloszgilga.lib.jmpsl.file.hashcode.FileHashCodeGenerator;

/**
 * Simple POJO class storing image sending payload (sending from application). This class implements
 * {@link IBufferedImagePayload} interface and override methods (by lombok annotation). Fields:
 *
 * <ul>
 *     <li><code>bytesRepresentation</code> - image as stream of array bytes</li>
 *     <li><code>preferredWidth</code> - image preferred width (resize by library)</li>
 *     <li><code>preferredHeight</code> - image preferred height (resize by library)</li>
 *     <li><code>id</code> - user id (from database)</li>
 *     <li><code>imageUniquePrefix</code> - user image prefix (avatar, banner etc.)</li>
 *     <li><code>userHashCode</code> - user hash code (generated by {@link FileHashCodeGenerator}, from database)</li>
 * </ul>
 *
 * @author Miłosz Gilga
 * @since 1.0.2
 */
@Data
@Builder
@AllArgsConstructor
public class BufferedImageSenderPayload implements IBufferedImagePayload {
    private byte[] bytesRepresentation;
    private int preferredWidth;
    private int preferredHeight;
    private Long id;
    private String imageUniquePrefix;
    private String userHashCode;
}
