/*
 * Copyright (c) 2023 by multiple authors
 *
 * File name: BufferedImageDeletePayload.java
 * Last modified: 03/11/2022, 00:29
 * Project name: jmps-library
 *
 * Licensed under the MIT license; you may not use this file except in compliance with the License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL
 * COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.
 */

package org.jmpsl.gfx.sender;

import lombok.*;

import org.jmpsl.file.hashcode.FileHashCodeGenerator;

/**
 * Simple POJO record representing structure for deleting user image from external SSH/SFTP static resources server.
 * Class has following parameters:
 *
 * <ul>
 *     <li><code>userHashCode</code> - user hash code (generated by {@link FileHashCodeGenerator}, from database)</li>
 *     <li><code>uniqueImagePrefix</code> - user image prefix (avatar, banner etc.)</li>
 *     <li><code>id</code> - user id (from database)</li>
 * </ul>
 *
 * @author Miłosz Gilga
 * @since 1.0.2
 */
@Builder
public record BufferedImageDeletePayload(String userHashCode, String uniqueImagePrefix, Long id) {
}
