/*
 * Copyright (c) 2023 by multiple authors
 *
 * File name: TempImageSavePayload.java
 * Last modified: 31/10/2022, 23:51
 * Project name: jmps-library
 *
 * Licensed under the MIT license; you may not use this file except in compliance with the License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL
 * COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE.
 */

package org.jmpsl.gfx.sender;

import lombok.*;

import org.jmpsl.gfx.*;
import org.jmpsl.file.hashcode.FileHashCodeGenerator;

/**
 * Simple POJO record representing temporary file informations for generated file and save on external SFTP server.
 * Stored following parameters:
 *
 * <ul>
 *     <li><code>bytesRepresentation</code> - image as stream of array bytes</li>
 *     <li><code>uniqueImagePrefix</code> - user image prefix (avatar, banner etc.)</li>
 *     <li><code>id</code> - user id (from database)</li>
 *     <li><code>extensionName</code> - image extension string representation (ex. png, jpeg etc.)</li>
 *     <li><code>userHashCode</code> - user hash code (generated by {@link FileHashCodeGenerator}, from database)</li>
 * </ul>
 *
 * @author Miłosz Gilga
 * @since 1.0.2
 */
@Builder
public record TempImageSavePayload(
    byte[] bytesRepresentation, String uniqueImagePrefix, Long id, String extensionName, String userHashCode
) {
    public TempImageSavePayload(byte[] bytes, IBufferedImagePayload payload, ImageExtension extension) {
        this(bytes, payload.getImageUniquePrefix(), payload.getId(), payload.getUserHashCode(),
            extension.getImageExtension());
    }
}
