/*
 * Copyright (c) 2023 by MULTIPLE AUTHORS
 *
 * File name: TempImageSavePayload.java
 * Last modified: 28/03/2023, 23:14
 * Project name: jmps-library
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 *     <http://www.apache.org/license/LICENSE-2.0>
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the license.
 */

package org.jmpsl.gfx.sender;

import lombok.Builder;

import org.jmpsl.gfx.ImageExtension;
import org.jmpsl.gfx.IBufferedImagePayload;
import org.jmpsl.file.hashcode.FileHashCodeGenerator;

/**
 * Simple POJO record representing temporary file informations for generated file and save on external SFTP server.
 * Stored following parameters:
 *
 * <ul>
 *     <li><code>bytesRepresentation</code> - image as stream of array bytes</li>
 *     <li><code>uniqueImagePrefix</code> - user image prefix (avatar, banner etc.)</li>
 *     <li><code>id</code> - user id (from database)</li>
 *     <li><code>extensionName</code> - image extension string representation (ex. png, jpeg etc.)</li>
 *     <li><code>userHashCode</code> - user hash code (generated by {@link FileHashCodeGenerator}, from database)</li>
 * </ul>
 *
 * @author Miłosz Gilga
 * @since 1.0.2
 */
@Builder
public record TempImageSavePayload(
    byte[] bytesRepresentation, String uniqueImagePrefix, Long id, String extensionName, String userHashCode
) {
    public TempImageSavePayload(byte[] bytes, IBufferedImagePayload payload, ImageExtension extension) {
        this(bytes, payload.getImageUniquePrefix(), payload.getId(), payload.getUserHashCode(),
            extension.getImageExtension());
    }
}
